# <center> <span style='color:#ff6655'>Ejercitación Módulo 6</span></center>

Módulo 6 - Parte teórica

**Profesor Adjunto:** Mag. Bioing. Baldezzari Lucas

<p style='text-align: left;'> V2022 </p>

<hr style="border:1px solid gray"> </hr>

### <span style='color:#16C79A'>1. Basics</span>

Implemente lo siguiente:

- 1.1) Cree un array de ceros -*vector nulo*- de 10 elementos.
- 1.2) Cree un vector nulo de 10 elementos donde el 6to elemento sea 1.
- 1.3) Cree un aray de 3x3x3 de valores enteros y aleatorios entre 1 y 20.
- 1.4) Cree un array de 5x5 y ordenelo por filas. Repita pero ordenando por columnas. Revise la documentación de *numpy*sort()*.
- 1.5) Considere un arreglo con shape *(6,7,8)*, ¿cuales son los índices *(x,y,z)* del elemento 100? 
- 1.6) Cree un array 2D que tenga valores 1 en sus bordes y cero dentro.
- 1.7) Cree un array de 8x8 y genere un patrón de tablero de ajedrez con ceros y unos. Un 0 representa un casillero blanco y un 1 representa un casillero negro.
- 1.8) Cree una matriz de 4x4 donde sus columnas tengan valores desde 1 a 4.
- 1.9) Cree un vector de 10 valores entre 0 y 1 (sin incluir los extremos).

In [1]:
import numpy as np 
#1.1
cero=np.zeros(10)
print(cero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
#1.2
cero[5]=1
print(cero)


[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [3]:
#1.3
random = np.random.randint(1,20, size = (3,3,3))
print(random)

[[[11  7 15]
  [10 11  4]
  [16  7 14]]

 [[ 4 13 14]
  [ 9 13  2]
  [ 6 17 13]]

 [[13 16  5]
  [ 3  2  9]
  [19 16 11]]]


In [4]:
#1.4
randomfive=np.random.randint(1,5, size=(5,5))
"Se muestra el array 5x5 con valores de 1 a 5"
print(randomfive) 
"Se ordena el array por filas"
filas=np.sort(randomfive,1)
print(filas)

print("###################################################################")

columnas=np.sort(randomfive,0)
print(columnas)

[[1 1 2 1 1]
 [1 1 1 4 1]
 [3 3 1 2 1]
 [3 1 1 2 1]
 [4 3 3 3 4]]
[[1 1 1 1 2]
 [1 1 1 1 4]
 [1 1 2 3 3]
 [1 1 1 2 3]
 [3 3 3 4 4]]
###################################################################
[[1 1 1 1 1]
 [1 1 1 2 1]
 [3 1 1 2 1]
 [3 3 2 3 1]
 [4 3 3 4 4]]


In [5]:
#1.5) Considere un arreglo con shape *(6,7,8)*, ¿cuales son los índices *(x,y,z)* del elemento 100?
"""
Voy a crear un array con valores de 0 a 56*6 que da iguala a 336 valores.
Luego realizo un reshape a ese array con la forma requerida por el ejercicio.
Para enontrar el indice del valor 100 utilizo el array ordenado y aplico el 
metodo Argwhere. 
"""

contarray = np.arange(336)
ordenados = np.reshape(contarray,(6,7,8))
lugar=np.argwhere(ordenados==100)
print(contarray)
print(lugar)

#arra=np.random.randint(1,100, size=(6,7,8))
#print(arra)
#print(arra.shape)
#print(np.ndim(arra))
#array= np.reshape(arra,(6*7*8))
#print(array[100])
#ran domfive=np.random.randint(1,5, size=(5,5))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [6]:
# 1.6) Cree un array 2D que tenga valores 1 en sus bordes y cero dentro.

arraceros= np.zeros((15,15))
print(arraceros)
lista=range(15)
np.put(arraceros,[lista],1)
print(arraceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

### <span style='color:#16C79A'>2. Sumarizing datos</span>

- 2.1) A partir de un array 2D la media total, la media a lo largo de las filas y la media a lo largo de las columnas. Agregue una columna con las medias por columna. Idem para filas.
- 2.2) Repita el punto anterior pero para el desvío estándar.
- 2.3) Carge una imágen RGB y genere otro array con los valores medios de los píxeles en cada canal.
- 2.4) Cree un array de 11x11 y llenelo de valores aleatorios enteros entre 1 y 100 y normalice sus valores. La normalización esta dada por,
$$ z_i = \frac{x_i - \bar{X}}{\sigma} $$
- 2.5) A partir de un array de números enteros, encuentre cual es valor que más se repite. Revise la función *nunmpy.unique()* para ayudarse.

### <span style='color:#16C79A'>3. Filtrando arrays</span>

- 3.1) Dado un array, reemplazar los elementos que estén entre 2 y 5 por su negado (positivos a negativos, y viceversa).
- 3.2) Obtener los índices de un arreglo 2D de enteros correspondientes a los valores que sean números primos.
- 3.3) Obtener un array con los índices correspondientes a aquellos valores que se repiten en dos arrays 1D.

    ```python
    ## Ejemplo 3.3

    a = np.array([1,2,3,4,5])
    b = np.array([1,4,4,4,5])

    ## el programa debe retornar un array con los valores
    ## [0,3,4]
    ```

### <span style='color:#16C79A'>4. Operaciones básicas con matrices</span>

- 4.1) A partir de un array 2D de valores aleatorios que representan coordenadas de puntos en el espacio 2D encontrar la distancia euclidiana punto a punto. Utilice *numpy.random.random()* para generar el array.
- 4.2) Calcule los valores medios de cada columna de una matriz 2D. Reste los valores medios calculados a sus correspondienes columnas.
- 4.3) Implemente una función que devuelva *True* si alguna columna de una matriz 2D posee una *columna nula*, donde una columna nula es aquella que esta compuesta de ceros.
- 4.4) Implemente una fucnión que devuelva el produco punto de dos matrices, en el caso de que estas no sean compatibles la función debe retornar None.
- 4.5) Implemente una función que devuelva la diagonal a partir del producto punto entre dos matrices cuadradas.
- 4.6) A partir de un array 2D cambie de posición de dos filas cualquiera.

### <span style='color:#16C79A'>5. Desafío</span>

- 5.1) A partir de un array 2D lleno de ceros, implemente una función que reemplace *p* elementos iguales a 1 en posiciones aleatorias del array. Utilice *numpy.put()* y *numpy.random.choice()*.
- 5.2) Ordene un array 2D en base a la *n-ésima* columna. Hint: Revise *numpy.argsort()* para resolver.
- 5.3) Genere una función llamada *mediaMovil()* que reciba como parámetro un array y un valor entero correspondiente a la cantidad de elementos a calcular la media. La función debe retornar un nuevo array con las medias móviles calculadas.
- 5.4) A partir de un array 1D obtenga un array con los valores correspondientes al "ranking" que ocupan los valores del array original, sin cambiar el orden (Hint: Se recomienda usar *numpy.argsort()*). Vea el ejemplo.

    ```python
    np.random.seed(42)
    a = np.random.randint(20, size=10)
    ## a es array([ 6, 19, 14, 10,  7,  6, 18, 10, 10,  3])
    
    ## salida esperada
    [1, 9, 7, 4, 3, 2, 8, 5, 6, 0]
    ```
    


In [7]:
# 5.1
import numpy as np
array=np.



SyntaxError: invalid syntax (Temp/ipykernel_9024/2146917999.py, line 3)

In [ ]:
#5.3 Ejemplo ahi vamos haciendo como si sabemos

import numpy as np

import matplotlib.pyplot as plt

ejarr=np.random.rand(170)

n = 3
#define la función de promedio móvil 
def moving_avg (ejarr, n):
    cumsum = np.cumsum (ejarr)
    return (cumsum [n:] - cumsum [: - n]) / float (n)

#calcular la media móvil utilizando los 3 períodos de tiempo anteriores

plt.plot(ejarr)
ejemplo=moving_avg(ejarr,25)
plt.plot(ejemplo)
plt.show()


### <span style='color:#16C79A'>6. Dividiendo una imágen en cuadrantes</span>

Cargue una imágen RGB y obtenga 4 arrays correspondientes a los cuatro cadrantes de la imágen.

### <span style='color:#16C79A'>7. Filtrando señal de plestimografía (obligatorio)</span>

Cargue la señal de fotoplestimografía utilizada en la guía de ejercicios del módulo 4 y apliquele la función *mediaMovil()* realizada en el ejercicio 5.3). ¿Hay algún cambio en la señal? ¿Qué tipo de filtro es una media movil?

### <span style='color:#16C79A'>8. Mejorando la clase *Image* y el módulo *procesImage* (obligatorio)</span>

Utilizando numpy y sus funcionalidades implemente una versión mejorada de la clase *Image* y las funciones dentro del módulo *procesImage* del ejercicio 6 de la guía de práctica del Módulo 4.

### <span style='color:#16C79A'>9. Analizando eficiencia energética en hogares (obligatorio)</span>

A continuación realizará el análisis de algunos parámetros acerca de los requerimientos para climatizar un hogar, ya sea para verano o invierno, es decir, la *eficiencia energética*. Usted cuenta con un [set de datos](https://archive.ics.uci.edu/ml/datasets/Energy+efficiency#) llamado *eficienciaEnergética.csv*, el cual contiene 10 columnas de datos, las cuales de izquierda a derecha son,

- 1) Compactación relativa: Medida de la compactación de la casa. Hogares mas compactos, menos espacios vacíos a los cuales enfriar o calentar. Los valores van de 0 a 1.
- 2) Superficie total: Superficie (en $m^2$) total del hogar.
- 3) Área de muros: Superficie total (en $m^2$) cubierta por muros.
- 4) Área de techos: Superficie total (en $m^2$) de techos.
- 5) Altura total: Algtura total (en $m$) de la casa.
- 6) Orientación de ventanas: Si las ventanas apuntan al norte (2), al sur (3),a l este (4) o al oeste (5).
- 7) Proporción de área de vidriado: Es la proporción de edificación que esta cubierta por aberturas de vidrio. En este set de datos puede tomar 4 valores, los mismos son, 0.0, 0.1, 0.25 y 0.4.
- 8) Distribución de ventanas: Distribución de ventanas en el hogar.
- 9) Carga para calentamiento: Cuanta carga (en KWatts) es necesario aportar al hogar para calentarlo.
- 10) Carga para enfriamiento: Cuanta carga (en KWatts) de frío es necesario aportar al hogar para enfriarlo.

A continuación se cargan los datos.

In [ ]:
## Cargando datos
import numpy as np
datos = np.genfromtxt('eficienciaEnergética.csv',delimiter=',',dtype = np.float64)

#### Responda

##### A) Generales
- A.1 ¿Cuantos hogares han sido utilizados en el set?
- A2. ¿Cuáles son los valores promedios de Área de Muros, Áreas de techos y Superficie total? También calcule los desvíos estándar.
- A3. ¿Cuales son los valores promedios y los desvíos estándar para las cargas de calentamiento y enfriamiento?

In [ ]:
## TODO A

##### B) Acerca de compactación relativa
- B1) ¿Cuál es el valor medio de compactación relativa?
- B2) ¿Cuál es la superficie total de la casa (o casas) con menor compactación? Idem para mayor compactación.

In [ ]:
## TODO B

##### C) Comparando proporción de área de vidriado con las carga de calentamiento y carga de enfriamiento.

- C1) ¿Cuantos hogares por cada valor de *proporción de área de vidriado* hay en el set?
- C2) Utilice *plt.hist()* de la librería *matplotlip.pyplot* para graficar el histograma de la columna *proporción de área de vidriado*.
- C3) Genere un array formado por las columnas de *proporción de área de vidriado*, la de *Carga para calentamiento* y la de *Carga para enfriamiento*.

In [ ]:
## TODO desde C1 a C3

- C4) A partir de la matriz generada en C3) encuentre el valor medio de la carga total de calentamiento y la de enfriamiento para cada valor de *proporción de área de vidriado*, guarde estos arrays en los arrays *promediosCalentamiento* y *promediosEnfiramiento*, respectivamente.

In [ ]:
### TODO C4
propVidriado = [0, 0.1, 0.25, 0.4]
promediosCalentamiento = ___
promediosEnfiramiento = ___

# ## Descomentar para graficar
# plt.plot(propVidriado, promediosCalentamiento, marker="P", label = "Calentamiento")
# plt.plot(propVidriado, promediosEnfiramiento, marker="^", label = "Enfriamiento")
# plt.title("Ventanas vs carga calentamiento y enfriamiento")
# plt.ylabel("Carga")
# plt.ylim((0,30))
# plt.xlabel("Proporción área de vidriado")
# plt.legend()
# plt.show()

##### D) Comparando superficies de los techos contra carga de calentamiento y carga de enfriamiento

- D1) ¿Cuántas áreas de techos diferentes hay en el set de datos? Guarde estos valores en un array llamado *roofAreas*. ¿Cuál es el promedio, en $m^2$ totales de todos los hogares?
- D2) ¿Cuantos hogares por cada valor encontrado en el punto D1) hay en el set?
- D3) Utilice *plt.hist()* de la librería *matplotlip.pyplot* para graficar el histograma de la columna *Área de techos*.
- D4) Genere un array formado por las columnas de *Área de techos*, la de *Carga para calentamiento* y la de *Carga para enfriamiento*.

In [ ]:
## TODO de D1 a D4

¿Qué conclusiones puede sacar del gráfico anterior acerca de la cantidad de carga de calor y de enfriamiento que se necesita en cada hogar respecto de las proporciones de ventanas vidriadas?

- D5) A partir de la matriz generada en D4) encuentre el valor medio de la carga total de calentamiento y la de enfriamiento para cada valor de *Área de techos*, guarde estos arrays en los arrays *promediosCalentamiento* y *promediosEnfiramiento*, respectivamente.

In [ ]:
### TODO D5
roofAreas = ___
promediosCalentamiento = ___
promediosEnfiramiento = ___

# ## Descomentar para graficar
# plt.plot(roofAreas, promediosCalentamiento, marker="P", label = "Calentamiento")
# plt.plot(roofAreas, promediosEnfiramiento, marker="^", label = "Enfriamiento")
# plt.title("Áreas de techos vs carga calentamiento y enfriamiento")
# plt.ylabel("Carga")
# plt.ylim((0,30))
# plt.xlabel("Proporción área de vidriado")
# plt.legend()
# plt.show()

¿Qué conclusiones puede sacar del gráfico anterior acerca de la cantidad de carga de calor y de enfriamiento que se necesita en cada hogar respecto del área total de los techos?

##### E) Comparando orientación de paredes contra carga de calentamiento y carga de enfriamiento

- E1) ¿Cuantas casas hay por cada una de las orientaciones (columna *orientación*)?
- E2) Utilice *plt.hist()* de la librería *matplotlip.pyplot* para graficar el histograma de la columna *Orientación de ventanas*.
- E3) Genere un array formado por las columnas de *Orientación de ventanas*, la de *Carga para calentamiento* y la de *Carga para enfriamiento*.

In [ ]:
## TODO de E1 a E3

- E4) A partir de la matriz generada en E#) encuentre el valor medio de la carga total de calentamiento y la de enfriamiento para cada valor de *Orientación de ventanas*, guarde estos arrays en los arrays promediosCalentamiento y promediosEnfiramiento, respectivamente.

In [ ]:
### TODO D5
orientaciones = [2,3,4,5] #norte, sur, este, oeste.
promediosCalentamiento = ___
promediosEnfiramiento = ___

# ## Descomentar para graficar
# plt.plot(orientaciones, promediosCalentamiento, marker="P", label = "Calentamiento")
# plt.plot(orientaciones, promediosEnfiramiento, marker="^", label = "Enfriamiento")
# plt.title("Orientaciones de ventana vs carga calentamiento y enfriamiento")
# plt.ylabel("Carga")
# plt.ylim((0,30))
# plt.xlabel("Orientaciones")
# plt.legend()
# plt.show()

<hr style="border:1px solid black"> </hr>

## Final Jupyter